# Generated by Django 4.2.1 on 2023-05-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expert_position_alter_expert_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='position',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='expert',
            name='use_state',
            field=models.BooleanField(default=1),
        ),
    ]
