# Generated by Django 4.2.1 on 2023-05-20 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_expert_description_alter_expert_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='expert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
