# Generated by Django 4.2.1 on 2023-05-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('desciption', models.CharField(max_length=255, null=True)),
                ('sheetname', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
