# Generated by Django 4.0.10 on 2023-05-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('desciption', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('squere', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('image', models.URLField(null=True)),
                ('specification', models.JSONField(null=True)),
                ('ref', models.CharField(db_index=True, max_length=30)),
                ('price', models.JSONField(db_index=True)),
                ('description', models.TextField(null=True)),
                ('advantage', models.CharField(max_length=255)),
                ('documentation', models.JSONField()),
                ('features', models.JSONField()),
                ('url', models.URLField()),
            ],
        ),
    ]
