# Generated by Django 4.0.10 on 2023-05-17 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obrasnet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='obrasnet.category'),
        ),
    ]
