# Generated by Django 4.0.10 on 2023-05-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrasnet', '0003_alter_material_advantage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='documentation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='features',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='specification',
            field=models.TextField(null=True),
        ),
    ]
