# Generated by Django 4.0.10 on 2023-05-17 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obrasnet', '0004_alter_material_documentation_alter_material_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapHistroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='obrasnet.category')),
            ],
        ),
    ]
