# Generated by Django 4.0.10 on 2023-05-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obrasnet', '0005_scraphistroy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='scraphistroy',
            old_name='category_id',
            new_name='category',
        ),
    ]
