# Generated by Django 4.0.10 on 2023-05-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrasnet', '0006_rename_category_id_material_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ScrapHistroy',
        ),
    ]
