# Generated by Django 4.0.10 on 2023-05-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrasnet', '0007_material_state_delete_scraphistroy'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sheetname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
