# Generated by Django 4.0.10 on 2023-05-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrasnet', '0009_material_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='advantage',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
