# Generated by Django 4.0.10 on 2023-05-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrasnet', '0011_alter_material_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
